{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Nombre de pi enregistrés",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lafayette_used_client_slots)"
    }
   ]
  },
  {
   "title": "Nombre de pi joignables",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"lafayette\"} == 1)"
    }
   ]
  },
  {
   "title": "Charge CPU des pi",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"lafayette\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM usage des pi",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"lafayette\"} - node_memory_MemFree_bytes{job=\"lafayette\"} - node_memory_Buffers_bytes{job=\"lafayette\"} - node_memory_Cached_bytes{job=\"lafayette\"}) / node_memory_MemTotal_bytes{job=\"lafayette\"}) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nombre d'admins enregistrés",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(lafayette_used_admin_slots)"
    }
   ]
  },
  {
   "title": "Température des pi",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by (instance) (rpi_temperature)\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Liste des pi en lignes (par IP)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "sum by (ip) (label_replace(up{job=\"lafayette\"} == 1, \"ip\", \"$1\", \"instance\", \"([0-9.]+):.*\"))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}